import Link from 'next/link';
import type { Project, Requirement } from '@/lib/project';
import { evidenceUrl } from '@/lib/project';
import ForecastForm from './forecast-form';

const nav = [
  { href: '/', label: 'Overview', icon: '◈' },
  { href: '/milestones', label: 'Milestones', icon: '◇' },
  { href: '/requirements', label: 'Requirements', icon: '▤' },
  { href: '/tasks', label: 'Task queue', icon: '☷' },
  { href: '/tests', label: 'Verification', icon: '◎' },
  { href: '/risks', label: 'Risks & blockers', icon: '△' },
  { href: '/prediction', label: 'Prediction', icon: '⌁' },
  { href: '/usage', label: 'AI usage', icon: '◷' },
  { href: '/decisions', label: 'Q&A & decisions', icon: '◌' },
  { href: '/changes', label: 'Change requests', icon: '＋' },
  { href: '/market', label: 'Market analysis', icon: '◫' },
  { href: '/integrations', label: 'Integrations', icon: '⊞' },
  { href: '/activity', label: 'Activity', icon: '↗' },
  { href: '/handoff', label: 'Handoff', icon: '⇥' },
];

const labels: Record<string,string> = { overview: 'Project overview', milestones: 'Milestones', requirements: 'Requirements', tasks: 'Task queue', tests: 'Verification', risks: 'Risks & blockers', prediction: 'Completion prediction', usage: 'AI usage & efficiency', decisions: 'Q&A & decisions', changes: 'Feature & change requests', market: 'Market analysis', integrations: 'Integrations', activity: 'Activity', handoff: 'Handoff' };
const statusTone = (status: string) => status === 'Verified' || status === 'Complete' ? 'green' : status === 'Failed' ? 'red' : status === 'Blocked' ? 'orange' : status === 'In progress' || status === 'Implemented' ? 'blue' : status === 'Deferred' ? 'muted' : 'muted';
const pct = (part: number, total: number) => total ? Math.round(part / total * 100) : 0;
const source = (path: string, label = 'View evidence') => <a className="evidence-link" href={evidenceUrl(path)} target="_blank" rel="noreferrer">{label} ↗</a>;

function Badge({ children, tone }: { children: React.ReactNode; tone?: string }) { return <span className={`tag ${tone || statusTone(String(children))}`}>{children}</span>; }
function SectionTitle({ eyebrow, title, action }: { eyebrow: string; title: string; action?: React.ReactNode }) { return <div className="section-heading"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div>{action}</div>; }
function Empty({ title, detail }: { title: string; detail: string }) { return <div className="empty"><span className="empty-mark">◇</span><h3>{title}</h3><p>{detail}</p></div>; }

function ProgressRing({ value, label, tone = 'amber' }: { value: number; label: string; tone?: string }) {
  const radius = 62; const circumference = 2 * Math.PI * radius;
  return <div className="ring-wrap"><svg viewBox="0 0 160 160" role="img" aria-label={`${label}: ${value}%`}><circle cx="80" cy="80" r={radius} className="ring-track" /><circle cx="80" cy="80" r={radius} className={`ring-progress ${tone}`} style={{ strokeDasharray: circumference, strokeDashoffset: circumference * (1 - value / 100) }} /></svg><div className="ring-center"><strong>{value}%</strong><span>{label}</span></div></div>;
}

function BarList({ rows, max, linkFor }: { rows: { label: string; value: number; tone?: string }[]; max: number; linkFor?: (label: string) => string }) {
  return <div className="bar-list">{rows.map(row => <div className="bar-row" key={row.label}><div className="bar-label"><span>{linkFor ? <Link href={linkFor(row.label)}>{row.label}</Link> : row.label}</span><b>{row.value}</b></div><div className="bar-track"><i className={row.tone || 'amber'} style={{ width: `${max ? row.value / max * 100 : 0}%` }} /></div></div>)}</div>;
}

function Overview({ p }: { p: Project }) {
  const m = p.metrics; const implemented = pct(m.v1Implemented, m.v1Applicable); const verified = pct(m.v1Verified, m.v1Applicable);
  const nextGate = p.milestones.find(x => x.id === 'M0')!;
  const buildRun = p.tests.find(t => t.id === 'QA-004' && t.result === 'Passed');
  const previewRun = p.tests.find(t => t.id === 'QA-005' && t.result === 'Passed');
  return <>
    <div className="hero-grid">
      <div className="panel hero-panel"><div className="hero-glow" /><p className="eyebrow">Engagement pulse · v1 public launch</p><h2>Building with proof,<br /><em>one gate at a time.</em></h2><p>Greenfield Groundbnb rebuild, tracked against the frozen 249-requirement contract. The Control Center is the first deliverable.</p><div className="hero-actions"><Link className="button primary" href="/milestones">Explore roadmap <span>→</span></Link><Link className="button ghost" href="/requirements">Inspect requirements</Link></div><div className="hero-footer"><span><i className="pulse-dot" /> Current phase: Control Center</span><span>Source checked 29 Sep 2026</span></div></div>
      <div className="panel release-panel"><p className="eyebrow">Release signal</p><div className="release-number">v1<span> / public launch</span></div><div className="release-gate"><span>Next product gate</span><strong>{nextGate.id} · {nextGate.name}</strong><p>{nextGate.gate}</p></div><div className="release-bottom"><Badge tone="orange">Gate not met</Badge><span>0 live checks recorded</span></div></div>
    </div>
    <div className="metric-grid">
      <Link className="metric-card" href="/requirements"><span>Binding requirements</span><strong>{m.total}</strong><small>249 unique IDs in frozen source ↗</small></Link>
      <Link className="metric-card" href="/requirements?status=Implemented"><span>Implemented · v1</span><strong>{implemented}%</strong><small>{m.v1Implemented} of {m.v1Applicable} applicable portions ↗</small></Link>
      <Link className="metric-card" href="/requirements?status=Verified"><span>Verified · v1</span><strong>{verified}%</strong><small>{m.v1Verified} evidenced portions ↗</small></Link>
      <Link className="metric-card" href="/tests"><span>Passing test runs</span><strong>{p.tests.filter(t => t.result === 'Passed').length}</strong><small>{p.tests.length ? `${p.tests.length} recorded runs` : 'No runs recorded yet'} ↗</small></Link>
    </div>
    <div className="overview-grid">
      <div className="panel progress-panel"><SectionTitle eyebrow="Delivery / v1 scope" title="Two measures. One honest view." action={<Link href="/requirements" className="small-link">Drill into ledger →</Link>} /><div className="rings"><ProgressRing value={implemented} label="Implemented" /><ProgressRing value={verified} label="Verified" tone="teal" /></div><p className="quiet">Implemented means code exists; Verified requires passing evidence. Mixed-tier rows contribute their v1 portion to these figures.</p></div>
      <div className="panel"><SectionTitle eyebrow="Contract coverage" title="Requirements by status" action={<span className="tag muted">All tiers</span>} /><BarList rows={m.statuses.map(s => ({ label: s.status, value: s.count, tone: s.status === 'Verified' ? 'teal' : s.status === 'Blocked' ? 'orange' : s.status === 'Failed' ? 'red' : 'blue' }))} max={m.total} linkFor={s => `/requirements?status=${encodeURIComponent(s)}`} /><p className="source-note">Source: {source('docs/ledger.csv', 'Requirement ledger')}</p></div>
    </div>
    <div className="overview-grid lower">
      <div className="panel"><SectionTitle eyebrow="Sequence" title="Milestone runway" action={<Link href="/milestones" className="small-link">All gates →</Link>} /><div className="runway">{p.milestones.slice(0, 7).map((x, i) => <Link href={`/milestones#${x.id}`} key={x.id} className={`runway-item ${i === 0 ? 'active' : ''}`}><span className="runway-dot">{i === 0 ? '◉' : '○'}</span><strong>{x.id}</strong><small>{x.name}</small></Link>)}</div><p className="quiet">M9 begins only after the v1 public-launch gate passes.</p></div>
      <div className="panel"><SectionTitle eyebrow="Attention" title="What needs a decision" action={<Link href="/decisions" className="small-link">Open Q&A →</Link>} />{p.questions.filter(q => q.status.startsWith('Open')).length ? <div className="attention-list">{p.questions.filter(q => q.status.startsWith('Open')).map(q => <div key={q.id}><Badge tone="orange">{q.id}</Badge><span>{q.topic}</span></div>)}</div> : <Empty title="No open questions" detail="New questions will appear with a source and owner." />}{source('docs/OPEN-DECISIONS.md', 'Question register')}</div>
    </div>
    <div className="overview-grid lower"><div className="panel"><SectionTitle eyebrow="Quality" title="Release readiness" action={<Link href="/tests" className="small-link">View verification →</Link>} /><div className="gate-list"><div><span>Specification locked</span><Badge tone="green">Hash recorded</Badge></div><div><span>Control Center build</span><Badge tone={buildRun ? 'green' : 'muted'}>{buildRun ? `Passed · ${buildRun.revision}` : 'Pending'}</Badge></div><div><span>Control Center preview</span><Badge tone={previewRun ? 'green' : 'muted'}>{previewRun ? `Checked · ${previewRun.revision}` : 'Pending'}</Badge></div><div><span>Live product integrations</span><Badge>Pending</Badge></div></div></div><div className="panel"><SectionTitle eyebrow="Research" title="Competitive landscape" action={<Link href="/market" className="small-link">Explore matrix →</Link>} /><div className="market-mini"><strong>{p.market.competitors.length}</strong><span>current products with dated primary-source records</span></div><p className="quiet">Opportunities are proposals; they do not change the contractual scope.</p></div></div>
  </>;
}

function Requirements({ p, filters = {} }: { p: Project; filters?: Record<string, string | undefined> }) {
  const visible = p.requirements.filter(r => (!filters.status || r.status === filters.status || (r.tier.includes('→') && r.v1_portion_status === filters.status)) && (!filters.tier || r.tier === filters.tier) && (!filters.milestone || r.milestone === filters.milestone) && (!filters.q || `${r.id} ${r.title}`.toLowerCase().includes(filters.q.toLowerCase())));
  return <><div className="panel intro-panel"><p className="eyebrow">Frozen contract / 249 IDs</p><h2>Trace every requirement to evidence.</h2><p>These rows are mechanically extracted from the source specification. Status and evidence live in the ledger; a test or live check is required before Verified.</p><div className="intro-tags"><Badge tone="green">v1 applicable {p.metrics.v1Applicable}</Badge><Badge tone="blue">Verified {p.metrics.v1Verified}</Badge><Badge tone="orange">Blocked {p.metrics.statuses.find(s => s.status === 'Blocked')?.count ?? 0}</Badge></div></div>
    <div className="panel"><div className="panel-head"><div><p className="eyebrow">Coverage ledger</p><h2>{visible.length} matching requirements</h2></div>{source('docs/ledger.csv', 'Open CSV')}</div><form className="filter-row" action="/requirements"><input name="q" aria-label="Search requirements" placeholder="Search ID or title" defaultValue={filters.q} /><select name="status" aria-label="Filter by status" defaultValue={filters.status || ''}><option value="">All statuses</option>{p.metrics.statuses.map(s => <option key={s.status}>{s.status}</option>)}</select><select name="tier" aria-label="Filter by tier" defaultValue={filters.tier || ''}><option value="">All tiers</option>{p.metrics.tiers.map(t => <option key={t.tier}>{t.tier}</option>)}</select><select name="milestone" aria-label="Filter by milestone" defaultValue={filters.milestone || ''}><option value="">All milestones</option>{p.milestones.map(m => <option key={m.id}>{m.id}</option>)}</select><button className="button primary" type="submit">Apply</button><Link className="button ghost" href="/requirements">Clear</Link></form>
      <div className="table-scroll"><table><thead><tr><th>ID</th><th>Requirement</th><th>Tier</th><th>Milestone</th><th>Status</th><th>Evidence</th></tr></thead><tbody>{visible.map(r => <tr key={r.id}><td><a href={evidenceUrl('docs/source/Groundbnb_Route_Planner_Agency_Spec_v3.0.md', r.source_line)} target="_blank" rel="noreferrer" className="id-link">{r.id} ↗</a></td><td className="requirement-title">{r.title}</td><td>{r.tier}</td><td><Link href={`/requirements?milestone=${r.milestone}`}>{r.milestone}</Link></td><td><Badge>{r.status}</Badge>{r.v1_portion_status && r.v1_portion_status !== r.status ? <small className="substatus">v1: {r.v1_portion_status}</small> : null}</td><td>{r.evidence ? <a href={r.evidence} target="_blank" rel="noreferrer">Open ↗</a> : <span className="quiet">None yet</span>}</td></tr>)}</tbody></table></div>
    </div></>;
}

function Milestones({ p }: { p: Project }) {
  return <><div className="panel intro-panel"><p className="eyebrow">Dependency-ordered delivery</p><h2>Gates before labels.</h2><p>A milestone completes only when its exit evidence passes. The Control Center is the first deliverable; Groundbnb M0 follows it.</p></div><div className="milestone-grid">{p.milestones.map((m, i) => <article className="panel milestone-card" id={m.id} key={m.id}><div className="milestone-top"><span className="milestone-index">{String(i + 1).padStart(2, '0')}</span><Badge>{m.status}</Badge></div><p className="eyebrow">{m.id} · {m.tier}</p><h2>{m.name}</h2><p>{m.gate}</p><div className="milestone-footer"><Link href={`/requirements?milestone=${m.id}`}>{p.requirements.filter(r => r.milestone === m.id).length} assigned IDs →</Link><a href={evidenceUrl(m.source.split('#')[0])} target="_blank" rel="noreferrer">Gate source ↗</a></div></article>)}</div></>;
}

function Tasks({ p }: { p: Project }) {
  return <><div className="panel intro-panel"><p className="eyebrow">Execution queue</p><h2>Small packets, durable handoffs.</h2><p>Each packet names the binding source, dependencies, checks, evidence destination, and exit gate. Agents start from repository state, not chat history.</p></div><div className="task-grid">{p.tasks.map((t, i) => <article className="panel task-card" key={t.path}><div className="task-top"><Badge tone={i === 0 ? 'blue' : 'muted'}>{i === 0 ? 'Current foundation' : 'Queued'}</Badge><span>{t.id}</span></div><h2>{t.title.replace(`${t.id} — `, '')}</h2><p>{t.id.startsWith('PCC') ? 'Project Control Center' : 'Groundbnb M0'}</p><a className="small-link" href={evidenceUrl(t.path)} target="_blank" rel="noreferrer">Read task packet ↗</a></article>)}</div></>;
}

function Tests({ p }: { p: Project }) {
  const categories = ['Unit','Static','Build','Integration','End-to-end','Fixture','Live provider','Visual','Accessibility'];
  return <><div className="panel intro-panel"><p className="eyebrow">Quality & release gates</p><h2>Evidence is the unit of progress.</h2><p>Passing a build is useful, but it does not verify every contractual outcome. Each run must name its revision, category, result, and artifact.</p></div><div className="metric-grid three"><div className="metric-card"><span>Recorded runs</span><strong>{p.tests.length}</strong><small>Repository QA evidence</small></div><div className="metric-card"><span>Passed</span><strong>{p.tests.filter(t => t.result === 'Passed').length}</strong><small>Revision-linked</small></div><div className="metric-card"><span>Failed</span><strong>{p.tests.filter(t => t.result === 'Failed').length}</strong><small>Open failures remain visible</small></div></div><div className="panel"><SectionTitle eyebrow="Test mix" title="Coverage by category" action={source('docs/qa/runs.json', 'QA register')} /><BarList rows={categories.map(label => ({ label, value: p.tests.filter(t => t.category === label).length, tone: 'teal' }))} max={Math.max(1, p.tests.length)} />{p.tests.length ? <div className="table-scroll"><table><thead><tr><th>Run</th><th>Category</th><th>Result</th><th>Revision</th><th>Date</th><th>Artifact</th></tr></thead><tbody>{p.tests.map(t => <tr key={t.id}><td>{t.id}</td><td>{t.category}</td><td><Badge>{t.result}</Badge></td><td>{t.revision}</td><td>{t.date}</td><td><a href={t.evidence}>Open ↗</a></td></tr>)}</tbody></table></div> : <Empty title="No test runs recorded" detail="The initial checks will appear here after the portal build and browser verification." />}</div></>;
}

function Risks({ p }: { p: Project }) {
  const risks = [
    { id: 'R-001', severity: 'High', title: 'Neon console identity and branch isolation', detail: 'Client named the project and database; the actual console identity and safe branch layout still need verification before schema changes.', source: 'docs/integrations.md' },
    { id: 'R-002', severity: 'High', title: 'Client workflow persistence', detail: 'Read-only portal can project repository files; authenticated submission and append-only audit need a verified durable server-side store.', source: 'docs/OPEN-DECISIONS.md' },
    { id: 'R-003', severity: 'Medium', title: 'No measured credit history', detail: 'Forecasts and model efficiency cannot be defended until usage and verified-task samples exist.', source: 'implementation-usage.csv' },
  ];
  return <><div className="panel intro-panel"><p className="eyebrow">Known constraints</p><h2>Risk is visible before release.</h2><p>These are current project-control risks, not defects in a shipped Groundbnb application. Requirement-level Blocked and Failed states remain in the ledger.</p></div><div className="risk-list">{risks.map(r => <article className="panel risk-card" key={r.id}><div><Badge tone={r.severity === 'High' ? 'orange' : 'blue'}>{r.severity}</Badge><span className="risk-id">{r.id}</span></div><h2>{r.title}</h2><p>{r.detail}</p>{source(r.source)}</article>)}</div><div className="panel"><SectionTitle eyebrow="Requirement blockers" title={`${p.requirements.filter(r => r.status === 'Blocked').length} blocked IDs`} />{p.requirements.some(r => r.status === 'Blocked') ? <RequirementMini rows={p.requirements.filter(r => r.status === 'Blocked')} /> : <Empty title="No requirement marked Blocked" detail="Unstarted work is not automatically a dependency blocker; concrete blockers will be recorded in the ledger." />}</div></>;
}

function RequirementMini({ rows }: { rows: Requirement[] }) { return <div className="table-scroll"><table><thead><tr><th>ID</th><th>Requirement</th><th>Notes</th></tr></thead><tbody>{rows.map(r => <tr key={r.id}><td>{r.id}</td><td>{r.title}</td><td>{r.notes || 'No note'}</td></tr>)}</tbody></table></div>; }

function Usage({ p }: { p: Project }) {
  const measured = p.usage.filter(u => u.platform_credits_delta && Number.isFinite(Number(u.platform_credits_delta)));
  const total = measured.length ? measured.reduce((sum, u) => sum + Number(u.platform_credits_delta), 0) : null;
  const byModel = [...new Set(measured.map(u => `${u.model} · ${u.reasoning_mode}`))].map(label => ({ label, value: measured.filter(u => `${u.model} · ${u.reasoning_mode}` === label).reduce((s,u) => s + Number(u.platform_credits_delta), 0) }));
  return <><div className="panel intro-panel"><p className="eyebrow">Agency implementation usage</p><h2>Measure verified output per credit.</h2><p>Codex/Work credits, API tokens, and product runtime usage are distinct. Empty values mean unavailable, never zero.</p></div><div className="metric-grid three"><div className="metric-card"><span>Measured credits</span><strong>{total === null ? '—' : total.toFixed(1)}</strong><small>{total === null ? 'No platform-reported data' : `${measured.length} attributed sessions`}</small></div><div className="metric-card"><span>Credits / verified v1 portion</span><strong>{total !== null && p.metrics.v1Verified ? (total / p.metrics.v1Verified).toFixed(1) : '—'}</strong><small>Requires measured attribution</small></div><div className="metric-card"><span>Model comparison</span><strong>{byModel.length || '—'}</strong><small>Comparable task classes needed</small></div></div><div className="overview-grid"><div className="panel"><SectionTitle eyebrow="Model / effort" title="Credit allocation" />{byModel.length ? <BarList rows={byModel} max={Math.max(...byModel.map(x => x.value))} /> : <Empty title="Insufficient observed data" detail="Model and effort efficiency appears after measured, comparable tasks are verified." />}</div><div className="panel"><SectionTitle eyebrow="Measurement quality" title="Attribution coverage" /><div className="large-unknown">Unknown</div><p className="quiet">No precise per-feature credit claims are made without task or session-level measurement.</p>{source('implementation-usage.csv', 'Usage ledger')}</div></div></>;
}

function Decisions({ p }: { p: Project }) {
  return <><div className="panel intro-panel"><p className="eyebrow">Client collaboration</p><h2>Questions, answers, and an audit trail.</h2><p>Questions remain open while independent work continues. Consequential choices never resolve automatically. The first portal release shows the repository record; authenticated response controls follow in PCC-02.</p></div><div className="overview-grid"><div className="panel"><SectionTitle eyebrow="Q&A queue" title={`${p.questions.filter(q => q.status.startsWith('Open')).length} open question`} action={source('docs/OPEN-DECISIONS.md', 'Question register')} /><div className="question-list">{p.questions.map(q => <article key={q.id}><div><strong>{q.id}</strong><Badge tone={q.status.startsWith('Answered') ? 'green' : 'orange'}>{q.status}</Badge></div><h3>{q.topic}</h3><p>{q.nextAction}</p></article>)}</div></div><div className="panel"><SectionTitle eyebrow="Governance" title="Response paths" /><div className="response-path"><b>Answer</b><p>Client supplies the decision directly.</p></div><div className="response-path"><b>Defer to AI</b><p>Explicit delegation; agent logs the decision and rationale.</p></div><div className="response-path"><b>Ignore for now</b><p>Independent work continues. Only noncritical defaults can be proposed for later review.</p></div><Badge tone="orange">Live submission pending PCC-02</Badge></div></div><div className="panel"><SectionTitle eyebrow="Append-only record" title="Decision history" action={source('docs/decisions/README.md', 'Decision contract')} /><div className="table-scroll"><table><thead><tr><th>ID</th><th>Source</th><th>Decision</th><th>Implementation</th><th>Date</th></tr></thead><tbody>{p.decisions.map(d => <tr key={d.id}><td>{d.id}</td><td><Badge tone="blue">{d.source}</Badge></td><td>{d.decision}</td><td>{d.implementationStatus}</td><td>{d.date}</td></tr>)}</tbody></table></div></div></>;
}

function Changes({ p }: { p: Project }) {
  const types = ['New feature','Enhancement','Clarification','Correction','UX request','Defect report','Scope change','Integration request','Research request'];
  return <><div className="panel intro-panel"><p className="eyebrow">Scope governance</p><h2>Ideas become reviewable requests.</h2><p>Requests are classified and assessed for requirement, architecture, data, testing, security, provider, credit, and calendar impact. The frozen source changes only through an approved amendment.</p></div><div className="metric-grid three"><div className="metric-card"><span>Total requests</span><strong>{p.changes.length}</strong><small>Recorded in repository</small></div><div className="metric-card"><span>Approved additions</span><strong>{p.changes.filter(x => x.status === 'Approved').length}</strong><small>Formal amendment required</small></div><div className="metric-card"><span>Scope growth</span><strong>{p.changes.filter(x => x.status === 'Approved').length ? 'Review' : '0'}</strong><small>Approved additions over baseline</small></div></div><div className="overview-grid"><div className="panel"><SectionTitle eyebrow="Intake taxonomy" title="What clients can submit" /><div className="chip-cloud">{types.map(x => <span className="tag muted" key={x}>{x}</span>)}</div><p className="quiet">Authenticated submission and triage controls are scheduled in PCC-02. This page does not claim a browser draft was submitted.</p></div><div className="panel"><SectionTitle eyebrow="Request register" title="Current queue" action={source('docs/changes/requests.json', 'Source record')} />{p.changes.length ? <div>{p.changes.map(c => <p key={c.id}>{c.id} · {c.title} · {c.status}</p>)}</div> : <Empty title="No requests recorded" detail="Approved changes will link to a formal amendment and affected requirement IDs." />}</div></div></>;
}

function Market({ p }: { p: Project }) {
  const columns = ['AI trip assistant','RV routing','Campground discovery','Collaborative editing','Offline access','Flight alerts','Marine charts'];
  const aliases: Record<string,string[]> = { 'AI trip assistant':['AI trip assistant','AI assistant','AI trip suggestions'], 'RV routing':['RV routing','RV-safe routes'], 'Campground discovery':['Campground discovery','Campground recommendations','Campground research'], 'Collaborative editing':['Collaborative editing','Collaboration'], 'Offline access':['Offline access','Offline maps','Offline trail maps','Offline map options','Offline downloaded charts'], 'Flight alerts':['Flight alerts'], 'Marine charts':['Marine charts'] };
  const categoryCounts = [...new Set(p.market.competitors.map(c => c.category))].map(category => ({ label: category, value: p.market.competitors.filter(c => c.category === category).length, tone: 'blue' }));
  return <><div className="panel intro-panel"><p className="eyebrow">Market intelligence · checked 29 Sep 2026</p><h2>Where the alternatives are strong.</h2><p>Current official product pages provide the evidence below. “Not assessed” means the capability was not established from the cited page; it is not a claim that the product lacks it.</p></div><div className="metric-grid three"><div className="metric-card"><span>Products reviewed</span><strong>{p.market.competitors.length}</strong><small>Primary-source records</small></div><div className="metric-card"><span>Categories</span><strong>{categoryCounts.length}</strong><small>Road, RV, itinerary, outdoor, marine</small></div><div className="metric-card"><span>Opportunity proposals</span><strong>{p.market.opportunities.length}</strong><small>Not approved scope</small></div></div><div className="panel"><SectionTitle eyebrow="Competitive feature map" title="Documented capabilities" action={source('docs/market/intelligence.json', 'Research record')} /><div className="table-scroll"><table className="matrix"><thead><tr><th>Product</th>{columns.map(x => <th key={x}>{x}</th>)}</tr></thead><tbody>{p.market.competitors.map(c => <tr key={c.name}><td><a href={c.sourceUrl} target="_blank" rel="noreferrer" className="id-link">{c.name} ↗</a><small>{c.category}</small></td>{columns.map(x => <td key={x}>{aliases[x].some(a => c.capabilities.includes(a)) ? <span className="matrix-yes" aria-label="Documented">●</span> : <span className="matrix-unknown" aria-label="Not assessed">—</span>}</td>)}</tr>)}</tbody></table></div><p className="source-note">● Documented on linked official page · — Not assessed. Capabilities and pricing can change.</p></div><div className="overview-grid"><div className="panel"><SectionTitle eyebrow="Market spread" title="Products by category" /><BarList rows={categoryCounts} max={p.market.competitors.length} /></div><div className="panel"><SectionTitle eyebrow="Groundbnb contract" title="Planned design strengths" /><ul className="strength-list"><li>Canonical trip state with auditable AI proposals</li><li>Land, RV, walking and marine planning in one hierarchy</li><li>Exact GPS destination distinct from road-access point</li><li>User-controlled portable exports and usage governance</li></ul><p className="quiet">These are specified Groundbnb goals, not shipped capabilities or proven exclusivity.</p></div></div><SectionTitle eyebrow="Product opportunity backlog" title="Ideas to evaluate, never automatic scope" /><div className="opportunity-grid">{p.market.opportunities.map(o => <article className="panel opportunity-card" key={o.id}><div><span className="eyebrow">{o.id} · {o.source}</span><Badge tone="blue">{o.disposition}</Badge></div><h2>{o.capability}</h2><p>{o.userProblem}</p><p className="proposal">{o.proposal}</p><footer><span>{o.complexity} complexity</span><span>{o.releaseTier}</span><a href={o.evidenceUrl} target="_blank" rel="noreferrer">Source ↗</a></footer></article>)}</div></>;
}

function Integrations({ p }: { p: Project }) {
  return <><div className="panel intro-panel"><p className="eyebrow">External dependencies</p><h2>Every connection has a state.</h2><p>Provider claims are checked against current official terms before use. A configured mock is never described as a live service.</p></div><div className="integration-grid">{p.integrations.map(i => <article className="panel integration-card" key={i.provider}><div className="integration-icon">⊞</div><div><p className="eyebrow">Provider</p><h2>{i.provider}</h2><p>{i.identity.replaceAll('`','')}</p><Badge tone={i.status.includes('exists') ? 'blue' : 'orange'}>{i.status}</Badge><small>{i.nextAction}</small></div></article>)}</div><p className="source-note">{source('docs/integrations.md', 'Dated integration register')}</p></>;
}

function Activity({ p }: { p: Project }) {
  return <><div className="panel intro-panel"><p className="eyebrow">Engineering chronology</p><h2>Only recorded events count.</h2><p>Commits, CI runs, deployments and milestone transitions will appear with exact revisions as they are recorded. Current display revision: {p.revision}.</p></div><div className="panel"><SectionTitle eyebrow="Timeline" title="Recent evidence" /><div className="timeline"><div><span className="timeline-dot" /><small>29 Sep 2026</small><h3>Specification frozen and ledger generated</h3><p>249 unique requirement IDs; SHA-256 recorded in repository state.</p>{source('docs/spec/SOURCE-HASH.txt')}</div><div><span className="timeline-dot" /><small>29 Sep 2026</small><h3>Neon identity answered by client</h3><p>Groundbnb project / groundbnb database; console verification remains pending.</p>{source('docs/decisions/D-001.json')}</div></div></div></>;
}

function Handoff({ p }: { p: Project }) {
  const links = [ ['Frozen specification','docs/source/Groundbnb_Route_Planner_Agency_Spec_v3.0.md'], ['Project state','docs/STATE.md'], ['Requirement ledger','docs/ledger.csv'], ['Task packets','docs/tasks/PCC-01-evidence-portal.md'], ['Open decisions','docs/OPEN-DECISIONS.md'], ['Integration register','docs/integrations.md'], ['QA evidence','docs/qa/README.md'], ['Implementation usage','implementation-usage.csv'] ];
  return <><div className="panel intro-panel"><p className="eyebrow">Continuity package</p><h2>Resume from the repository.</h2><p>Project memory, decisions, tests, deployment evidence, and next actions belong in versioned files. The checked preview revision is recorded in QA evidence.</p></div><div className="handoff-grid">{links.map(([label,path]) => <a className="panel handoff-link" href={evidenceUrl(path)} target="_blank" rel="noreferrer" key={path}><span>↗</span><strong>{label}</strong><small>{path}</small></a>)}</div><div className="panel"><SectionTitle eyebrow="Current status" title={`Revision ${p.revision}`} /><p className="quiet">M0 remains open. No Groundbnb product release or acceptance is claimed. See the current state file for dependency order and open constraints.</p></div></>;
}

function Prediction({ p }: { p: Project }) {
  const measured = p.usage.filter(u => u.platform_credits_delta && Number.isFinite(Number(u.platform_credits_delta)));
  const total = measured.length ? measured.reduce((s,u) => s + Number(u.platform_credits_delta), 0) : null;
  return <><div className="panel intro-panel"><p className="eyebrow">Capacity forecast</p><h2>Two rhythms. Visible uncertainty.</h2><p>The minimum-dwell scenario resumes as soon as allowance is available. Consistent dwell uses the observed median wait after eligibility. Dates stay blank when inputs are insufficient.</p></div><ForecastForm measuredCredits={total} verified={p.metrics.v1Verified} applicable={p.metrics.v1Applicable} /><div className="panel formula-panel"><p className="eyebrow">Transparent calculation</p><p><code>effective weekly capacity = min(weekly capacity, five-hour capacity × 168 ÷ (5 + dwell hours))</code></p><p className="quiet">Remaining credits ÷ effective weekly capacity × 7 days, plus any current mandatory wait. Manual numbers stay on this device and do not alter the project ledger.</p></div></>;
}

export default function Dashboard({ view, project: p, filters }: { view: string; project: Project; filters?: Record<string, string | undefined> }) {
  const title = labels[view] || labels.overview;
  return <div className="app-shell"><a className="skip-link" href="#main">Skip to content</a><aside className="sidebar"><Link href="/" className="brand" aria-label="Groundbnb Control Center home"><span className="brand-mark">⌂</span><span><strong>Groundbnb</strong><small>PROJECT CONTROL CENTER</small></span></Link><div className="sidebar-project"><span className="project-avatar">G</span><span><b>Groundbnb rebuild</b><small>Agency engagement</small></span><span className="sidebar-chevron">⌄</span></div><p className="nav-caption">WORKSPACE</p><nav aria-label="Main navigation">{nav.map(item => <Link key={item.href} href={item.href} aria-current={(view === 'overview' && item.href === '/') || item.href === `/${view}` ? 'page' : undefined} className={`nav-link ${((view === 'overview' && item.href === '/') || item.href === `/${view}`) ? 'active' : ''}`}><span className="nav-icon">{item.icon}</span>{item.label}</Link>)}</nav><div className="sidebar-bottom"><div className="sidebar-status"><i className="pulse-dot" /><div><strong>Evidence mode</strong><small>Repository-sourced</small></div></div><p>Spec v3.0 · {p.requirements.length} IDs<br />Revision {p.revision}</p></div></aside>
    <div className="workspace"><header className="topbar"><div className="breadcrumb"><span>Groundbnb</span><span className="crumb-sep">/</span><strong>{title}</strong></div><div className="topbar-right"><span className="topbar-live"><i className="pulse-dot" /> Project evidence</span><a href={evidenceUrl('docs/STATE.md')} target="_blank" rel="noreferrer" className="topbar-source">View project state ↗</a></div></header><main id="main" className="main-content"><div className="page-heading"><div><p className="eyebrow">AI AGENCY / DELIVERY INTELLIGENCE</p><h1>{title}</h1><p>{view === 'overview' ? 'A clear view of scope, progress, evidence, and the next decision.' : 'Grounded in the frozen specification and current repository records.'}</p></div><div className="page-date"><span>AS OF</span><strong>29 SEP 2026</strong></div></div>
      {view === 'overview' ? <Overview p={p} /> : view === 'milestones' ? <Milestones p={p} /> : view === 'requirements' ? <Requirements p={p} filters={filters} /> : view === 'tasks' ? <Tasks p={p} /> : view === 'tests' ? <Tests p={p} /> : view === 'risks' ? <Risks p={p} /> : view === 'usage' ? <Usage p={p} /> : view === 'prediction' ? <Prediction p={p} /> : view === 'decisions' ? <Decisions p={p} /> : view === 'changes' ? <Changes p={p} /> : view === 'market' ? <Market p={p} /> : view === 'integrations' ? <Integrations p={p} /> : view === 'activity' ? <Activity p={p} /> : <Handoff p={p} />}
      <footer className="site-footer"><span>Groundbnb · AI Agency Project Control Center</span><span>Evidence over estimates · Source v3.0 · {p.revision}</span></footer></main></div></div>;
}
